# duochrome.toml
#
# A theme tribute to the amber and green monochrome displays of yesteryear.
# Helix version 1.0 20203-10-18
#
# author/maintainer: Dan (github.com/d2718)

# # Syntax Scopes

# * - Class attributes, HTML tag attributes
"attribute" = "subgreen"

"type" = { modifiers = ["bold"] }
# * Primitive types provided by the language (int, usize)
"type.builtin" = { bg = "dkbrown", modifiers = ["bold"] }
"type.enum" = { modifiers = ["bold"] }
"type.enum.variant" = { modifiers = [] }

#"constructor"

"constant" = "maxgreen"
# * Special constants provided by the language (true, false, nil etc)
"constant.builtin" = { fg = "maxgreen", bg = "dkbrown" }
#"constant.builtin.boolean"
"constant.character" = "orange"
#"constant.character.escape"
#"constant.numeric"
#"constant.numeric.integer"
#"constant.numeric.float"

"string" = "subgreen"
"string.regexp" = { fg = "subgreen", bg = "dkbrown" }
#"string.special"
#"string.special.path"
"string.special.url" = { fg = "subgreen", underline = { style = "line" } }
# * Erlang/Elixir atoms, Ruby symbols, Clojure keywords
"string.special.symbol" = "maxgreen"

# * Comments
"comment" = "grey"
# * Single line comments (//)
#"comment.line"
# * Block comments (e.g. (/* */)
#"comment.block"
# * Documentation comments (e.g. /// in Rust)
#"comment.block.documentation"

#"variable"
# * Reserved language variables (self, this, super, etc.)
"variable.builtin" = { modifiers = ["italic"] }
# * Function parameters
"variable.parameter" = "amber"
#"variable.other"  # ??? IDK ???
# * Fields of composite data types (e.g. structs, unions)
#"variable.other.member"

#"label"

"punctuation" = "subgreen"
# * Commas, colons
#"punctuation.delimiter"
# * Parentheses, angle brackets, etc.
#"punctuation.bracket"
# * String interpolation brackets.
#"punctuation.special"

"keyword" = "orange"
#"keyword.control"
# * if, else
#"keyword.control.conditional"
# * for, while, loop
#"keyword.control.repeat"
# * import, export
#"keyword.control.import"
#"keyword.control.return"
#"keyword.control.exception"
# * or, in
#"keyword.operator"
# * Preprocessor directives (#if in C)
#"keyword.directive"
# * fn, func
#"keyword.function"
# * Keywords describing how things are stored
#"keyword.storage"
# * The type of something, class, function, var, let, etc.
#"keyword.storage.type"
# * Storage modifiers like static, mut, const, ref, etc.
"keyword.storage.modifier" = { fg = "bramber", modifiers = ["italic"] }

# * ||, +=, >
"operator" = "orange"

#"function"
#"function.builtin"
#"function.method"
"function.macro" = { fg = "orange", modifiers = ["bold"], underline = { style = "dotted"} }
# * (preprocessor in C)
#"function.special"

# * Tags (e.g. <body> in HTML)
"tag" = { modifiers = ["bold"] }
#"tag.builtin"

#"namespace"

#"special"  # ??? IDK ???

#"markup"
"markup.heading" = { modifiers = ["bold"] }
"markup.heading.marker" = { fg = "maxgreen", modifiers = ["bold"] }
#"markup.heading.1"    # heading text for h1 through h6
#"markup.heading.2"
#"markup.heading.3"
#"markup.heading.4"
#"markup.heading.5"
#"markup.heading.6" 
"markup.list" = "orange"
#"markup.list.unnumbered"
#"markup.list.numbered"
#"markup.list.checked"
#"markup.list.unchecked"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
#"markup.link"
# * URLs pointed to by links
"markup.link.url" = { fg = "subgreen", underline = { style = "line" } }
# * non-URL link references
"markup.link.label" = { fg = "subgreen", modifiers = ["italic"] }
# * URL and image descriptions in links
"markup.link.text" = "orange"
"markup.quote" = "orange"
"markup.raw" = "grey"
#"markup.raw.inline"
#"markup.raw.block"

# * version control changes
#"diff"
"diff.plus" = "green"
"diff.minus" = "orange"
"diff.delta" = "grey"
#"diff.delta.moved"

# # UI Elements

# * The following markup scopes are used for themeing the editor interface.
#"markup.normal"
#"markup.normal.completion"        # for completion doc popup UI
#"markup.normal.hover"             # for hover popup UI
# * markup.heading    [already defined above]
#"markup.heading.completion"       # for completion doc popup UI
#"markup.heading.hover"            # for hover popup UI
# * markup.raw        [ already defined above]
# * markup.raw.inline [ already defined above]
#"markup.raw.inline.completion"    # for completion doc popup UI
#"markup.raw.inline.hover"         # for hover popup UI

"ui.background" = { bg = "black" }
# * Picker separator below input line
#"ui.background.separator"

"ui.cursor" = { fg = "black", bg = "green" }
#"ui.cursor.normal"    
"ui.cursor.insert" = { bg = "amber", fg = "dimgreen" }
"ui.cursor.select" = { bg = "dkgreen", fg = "amber"}
# * Matching bracket etc.    
"ui.cursor.match" = { bg = "dkgreen", fg = "amber" }
# * Cursor with primary selection
#"ui.cursor.primary"
#"ui.cursor.primary.normal"
"ui.cursor.primary.insert" = { bg = "amber", fg = "dimgreen" }
"ui.cursor.primary.select" = { bg = "dkgreen", fg = "amber"}

# * Breakpoint indicator, found in the gutter
#"ui.debug.breakpoint"
# * Indicator for the line at which debugging execution is paused at, found in the gutter
#"ui.debug.active"
#"ui.gutter"
# * Gutter for the line the cursor is on
#"ui.gutter.selected"
# * Line at which debugging execution is paused at
#"ui.highlight.frameline"
# * Line numbers
"ui.linenr" = "medgreen"
# * Line number for the line the cursor is on
"ui.linenr.selected" = "amber"

# * Statusline
"ui.statusline" = { bg = "dimgreen", fg = "amber" }
# * Statusline (unfocused document)
"ui.statusline.inactive" = { bg = "dimbrown", fg = "green" }
# * Statusline mode during normal mode (only if editor.color-modes is enabled)
#"ui.statusline.normal"
# * Statusline mode during insert mode (only if editor.color-modes is enabled)
"ui.statusline.insert" = { bg = "amber", fg = "dimgreen" }
# * Statusline mode during select mode (only if editor.color-modes is enabled)
"ui.statusline.select" = { bg = "dkgreen", fg = "amber" }
# * Separator character in statusline
#"ui.statusline.separator"

# * Documentation popups (e.g. Space + k)
"ui.popup" = { bg = "dimbrown", fg = "subgreen" }
# * Prompt for multiple key options
"ui.popup.info" = { fg = "amber "}
# * Borderlines separating splits
"ui.window" = { bg = "dimbrown", fg = "subgreen" }
# * Description box for commands
"ui.help" = { bg = "dimbrown", fg = "subgren" }
# * Command prompts, popup text, etc.
"ui.text" = "green"
#"ui.text.focus"  
# * Same as ui.text but when the text is inactive (e.g. suggestions)
"ui.text.inactive" = { bg = "dimgreen", fg = "subgreen" }
# * The key: command text in ui.popup.info boxes
"ui.text.info" = { bg = "dimbrown", fg = "subgreen" }

"ui.virtual" = "brown"
# * Ruler columns (see the editor.rulers config)
"ui.virtual.ruler" = { bg = "dimgreen", fg = "green" }
#"ui.virtual.whitespace"
#"ui.virtual.indent-guide"
# * Default style for inlay hints of all kinds
"ui.virtual.inlay-hint" = "grey"
# * Style for inlay hints of kind parameter (LSPs are not required to set a kind)
#"ui.virtual.inlay-hint.parameter"
# * Style for inlay hints of kind type (LSPs are not required to set a kind)
#"ui.virtual.inlay-hint.type"
# * Soft-wrap indicator (see the editor.soft-wrap config)
#"ui.virtual.wrap"

# * Code and command completion menus
"ui.menu" = { bg = "dimbrown", fg = "green" }
# * Selected autocomplete item
"ui.menu.selected" = { bg = "dkgreen", fg = "bramber" }
# * fg sets thumb color, bg sets track color of scrollbar
#"ui.menu.scroll"
# * For selections in the editing area
"ui.selection" = { bg = "dkgreen" }
#"ui.selection.primary"
# * Highlighted lines in the picker preview
"ui.highlight" = "amber"

# * The next four only matter if editor.cursorline is enabled in config.
"ui.cursorline.primary" = { bg = "dimgreen" }       # The line of the primary cursor
#"ui.cursorline.secondary"     # The lines of any other cursors
"ui.cursorcolumn.primary" = { bg = "dimgreen" }     # The column of the primary cursor
#"ui.cursorcolumn.secondary"   # The columns of any other cursors

# * The next four are for gutter indicators.
"warning" = "gold"
"error" = "bramber"
"info" = "subgreen"
"hint" = "grey"
# * For diagnostic indication in the editing area
#"diagnostic"
"diagnostic.hint" = { underline = { style = "curl", color = "grey" } }
"diagnostic.info" = { underline = { style = "curl", color = "subgreen" } }
"diagnostic.warning" = { underline = { style = "curl", color = "gold" } }
"diagnostic.error" = { underline = { style = "curl", color = "bramber" } }

[palette]
black = "#000000"
grey  = "#809080"

dimgreen = "#002000"
dkgreen  = "#004000"
medgreen = "#008000"
subgreen = "#00a000"
green    = "#00c000"
maxgreen = "#00e000"

dimbrown = "#1c1402"
dkbrown  = "#392804"
brown    = "#563c06"
gold     = "#735108"
orange   = "#906508"
amber    = "#d89810"
bramber  = "#eac860"
