# poisonberry.toml
#
# A Helix theme in unhealthy purples and greens, inspired by the Witch
# Hazel themes (https://github.com/theacodes/witchhazel).
#
# v 0.2, 2023-10-30
#
# author/maintainer: Dan (github.com/d2718)

## UI Elements

"ui.background" = { bg = "darkest" }
# * Picker separator below input line
#"ui.background.separator"
# * Command prompts, popup text, etc.
"ui.text" = "calamine"
#"ui.text.focus"  
# * Same as ui.text but when the text is inactive (e.g. suggestions)
#"ui.text.inactive"
# * The key: command text in ui.popup.info boxes
#"ui.text.info"

# * Documentation popups (e.g. Space + k)
#"ui.popup"
# * Prompt for multiple key options
#"ui.popup.info"
# * Borderlines separating splits
#"ui.window"
# * Description box for commands
#"ui.help"

#"ui.cursor"
"ui.cursor.normal" = { fg = "darkest", bg = "calamine" }
"ui.cursor.insert" = { fg = "brightest", bg = "green" }
"ui.cursor.select" = { fg = "darkest", bg = "yellow" }
# * Matching bracket etc.    
"ui.cursor.match" = { fg = "blue", bg = "dimmed" }
# * Cursor with primary selection
#"ui.cursor.primary"
#"ui.cursor.primary.normal"    
#"ui.cursor.primary.insert"    
#"ui.cursor.primary.select"

# * For selections in the editing area
"ui.selection" = { bg = "dimgreen" }
#"ui.selection.primary"

# * The next four only matter if editor.cursorline is enabled in config.
"ui.cursorline.primary" = { bg = "dimpurple" }   # The line of the primary cursor
#"ui.cursorline.secondary"     # The lines of any other cursors
"ui.cursorcolumn.primary" = { bg = "dimpurple" } # The column of the primary cursor
#"ui.cursorcolumn.secondary"   # The columns of any other cursors

# * Statusline
"ui.statusline" = { bg = "dimpurple", fg = "dimmed" }
# * Statusline (unfocused document)
"ui.statusline.inactive" = "grey"
# * Statusline mode during normal mode (only if editor.color-modes is enabled)
#"ui.statusline.normal"
# * Statusline mode during insert mode (only if editor.color-modes is enabled)
"ui.statusline.insert" = { bg = "green", fg = "brightest" }
# * Statusline mode during select mode (only if editor.color-modes is enabled)
"ui.statusline.select" = { fg = "calamine", bg = "dimgreen" }
# * Separator character in statusline
"ui.statusline.separator" = "grey"

# * Line numbers
#"ui.linenr"
# * Line number for the line the cursor is on
"ui.linenr.selected" = "calamine"
"ui.gutter" = { bg = "dimpurple", fg = "dimmed" }
# * Gutter for the line the cursor is on
#"ui.gutter.selected"

# * Code and command completion menus
"ui.menu" = { bg = "dimpurple", fg = "calamine" }
# * Selected autocomplete item
"ui.menu.selected" = { bg = "dimgreen", fg = "brightest" }
# * fg sets thumb color, bg sets track color of scrollbar
#"ui.menu.scroll"

"ui.virtual" = "grey"
# * Ruler columns (see the editor.rulers config)
"ui.virtual.ruler" = { bg = "dimpurple" }
#"ui.virtual.whitespace"
#"ui.virtual.indent-guide"
# * Default style for inlay hints of all kinds
#"ui.virtual.inlay-hint"
# * Style for inlay hints of kind parameter (LSPs are not required to set a kind)
#"ui.virtual.inlay-hint.parameter"
# * Style for inlay hints of kind type (LSPs are not required to set a kind)
#"ui.virtual.inlay-hint.type"
# * Soft-wrap indicator (see the editor.soft-wrap config)
#"ui.virtual.wrap"

# * Highlighted lines in the picker preview
"ui.highlight" = { bg = "dimgreen", fg = "brightest" }

# * Breakpoint indicator, found in the gutter
#"ui.debug.breakpoint"
# * Indicator for the line at which debugging execution is paused at, found in the gutter
#"ui.debug.active"
# * Line at which debugging execution is paused at
#"ui.highlight.frameline"

# * The next four are for gutter indicators.
"warning" = "yellow"
"error"   = "red"
"info"    = "blue"
"hint"    = "dimmed"
# * For diagnostic indication in the editing area
#"diagnostic"
"diagnostic.hint" = { underline = { style = "curl", color = "dimmed" } }
"diagnostic.info" = { underline = { style = "curl", color = "blue" } }
"diagnostic.warning" = { underline = { style = "curl", color = "yellow" } }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }

# * version control changes
#"diff"
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "calamine"
"diff.delta.moved" = "grey"

## Syntax Scopes

# * - Class attributes, HTML tag attributes
"attribute" = "blue"

"type" = { modifiers = ["bold"] }
# * Primitive types provided by the language (int, usize)
"type.builtin" = { modifiers = ["italic"] }
#"type.enum"
"type.enum.variant" = { modifiers = [] }

#"constructor"

"constant" = "brightest"
# * Special constants provided by the language (true, false, nil etc)
"constant.builtin" = { fg = "brightest", modifiers = ["bold"] }
#"constant.builtin.boolean"
"constant.character" = "yellow"
#"constant.character.escape"
#"constant.numeric"
#"constant.numeric.integer"
#"constant.numeric.float"

"string" = "purple"
"string.regexp" = { fg = "purple", underline = { style = "dotted", color = "dimmed" } }
#"string.special"
#"string.special.path"
#"string.special.url"
# * Erlang/Elixir atoms, Ruby symbols, Clojure keywords
"string.special.symbol" = "brightest"

# * Comments
"comment" = "dimmed"
# * Single line comments (//)
#"comment.line"
# * Block comments (e.g. (/* */)
#"comment.block"
# * Documentation comments (e.g. /// in Rust)
"comment.block.documentation" = { fg = "dimmed", bg = "dimblue" }

#"variable"
# * Reserved language variables (self, this, super, etc.)
"variable.builtin" = { fg = "blue", modifiers = ["italic"] }
# * Function parameters
"variable.parameter" = "blue"
#"variable.other"  # ??? IDK ???
# * Fields of composite data types (e.g. structs, unions)
#"variable.other.member"

"label" = { fg = "brightest", modifiers = ["bold"] }

"punctuation" = "yellow"
# * Commas, colons
#"punctuation.delimiter"
# * Parentheses, angle brackets, etc.
#"punctuation.bracket"
# * String interpolation brackets.
#"punctuation.special"

"keyword" = "green"
#"keyword.control"
# * if, else
#"keyword.control.conditional"
# * for, while, loop
#"keyword.control.repeat"
# * import, export
#"keyword.control.import"
#"keyword.control.return"
#"keyword.control.exception"
# * or, in
#"keyword.operator"
# * Preprocessor directives (#if in C)
#"keyword.directive"
# * fn, func
#"keyword.function"
# * Keywords describing how things are stored
#"keyword.storage"
# * The type of something, class, function, var, let, etc.
#"keyword.storage.type"
# * Storage modifiers like static, mut, const, ref, etc.
"keyword.storage.modifier" = "red"

# * ||, +=, >
"operator" = "yellow"

#"function"
#"function.builtin"
#"function.method"
"function.macro" = { fg = "red", modifiers = ["bold"] }
# * (preprocessor in C)
#"function.special"

# * Tags (e.g. <body> in HTML)
"tag" = { modifiers = ["bold"] }
#"tag.builtin"

#"namespace"

#"special"  # ??? IDK ???

#"markup"
"markup.heading" = { fg = "brightest", modifiers = ["bold"] }
#"markup.heading.marker"
#"markup.heading.1"    # heading text for h1 through h6
#"markup.heading.2"
#"markup.heading.3"
#"markup.heading.4"
#"markup.heading.5"
#"markup.heading.6" 
"markup.list" = "yellow"
#"markup.list.unnumbered"
#"markup.list.numbered"
#"markup.list.checked"
#"markup.list.unchecked"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
#"markup.link"
# * URLs pointed to by links
"markup.link.url" = { underline = { style = "line" } }
# * non-URL link references
"markup.link.label" = { underline = { style = "line"}, modifiers = ["italic"] }
# * URL and image descriptions in links
"markup.link.text" = "purple"
"markup.quote" = { fg = "purple", modifiers = "italic" }
"markup.raw" = "brgrey"
#"markup.raw.inline"
#"markup.raw.block"

# * The following markup scopes are used for themeing the editor interface.
#"markup.normal"
#"markup.normal.completion"        # for completion doc popup UI
#"markup.normal.hover"             # for hover popup UI
# * markup.heading    [already defined above]
#"markup.heading.completion"       # for completion doc popup UI
#"markup.heading.hover"            # for hover popup UI
# * markup.raw        [ already defined above]
# * markup.raw.inline [ already defined above]
#"markup.raw.inline.completion"    # for completion doc popup UI
#"markup.raw.inline.hover"         # for hover popup UI

[palette]
darkest  = "#100818"
dimpurple = "#282030"
purple   = "#6860b0"
dimmed   = "#706b74"
calamine = "#a09ca4"

grey = "#707070"
brgrey = "#989898"

dimgreen  = "#204038"
green     = "#40b090"
yellow    = "#90b040"
brightest = "#b8c8c0"

dimblue = "#081828"
blue = "#4090b0"

red = "#b04060"
