# sunset.toml
#
# A Helix theme in blues and oranges.
#
# author/maintainer: Dan (github.com/d2718)

# # Syntax Scopes

# * - Class attributes, HTML tag attributes
"attribute" = "pomelo"

"type" = { modifiers = ["bold"] }
# * Primitive types provided by the language (int, usize)
"type.builtin" = { fg = "lining", modifiers = ["bold"] }
#"type.enum"
"type.enum.variant" = { modifiers = [] } 

#"constructor"

"constant" = "sky"
# * Special constants provided by the language (true, false, nil etc)
"constant.builtin" = { fg = "sky", modifiers = ["italic"] }
#"constant.builtin.boolean"
"constant.character" = { fg = "mountain", modifiers = ["bold"] }
"constant.character.escape" = { fg = "mountain", modifiers = ["bright"] }
#"constant.numeric"
#"constant.numeric.integer"
#"constant.numeric.float"

"string" = "mountain"
"string.regexp" = { fg = "mountain", modifiers = ["italic"] }
#"string.special"
#"string.special.path"
#"string.special.url"
# * Erlang/Elixir atoms, Ruby symbols, Clojure keywords
"string.special.symbol" = "lining"

# * Comments
"comment" = "melville"
# * Single line comments (//)
#"comment.line"
# * Block comments (e.g. (/* */)
#"comment.block"
# * Documentation comments (e.g. /// in Rust)
#"comment.block.documentation"

#"variable"
# * Reserved language variables (self, this, super, etc.)
"variable.builtin" = { fg = "lining", modifiers = ["italic"] }
# * Function parameters
"variable.parameter" = "lining"
#"variable.other"  # ??? IDK ???
# * Fields of composite data types (e.g. structs, unions)
"variable.other.member" = "pomelo"

"label" = { modifiers = ["bold"], underline = { style = "dotted" } }

"punctuation" = "pomelo"
# * Commas, colons
#"punctuation.delimiter"
# * Parentheses, angle brackets, etc.
#"punctuation.bracket"
# * String interpolation brackets.
#"punctuation.special"

"keyword" = "fire"
#"keyword.control"
# * if, else
#"keyword.control.conditional"
# * for, while, loop
#"keyword.control.repeat"
# * import, export
#"keyword.control.import"
#"keyword.control.return"
#"keyword.control.exception"
# * or, in
#"keyword.operator"
# * Preprocessor directives (#if in C)
#"keyword.directive"
# * fn, func
#"keyword.function"
# * Keywords describing how things are stored
#"keyword.storage"
# * The type of something, class, function, var, let, etc.
#"keyword.storage.type"
# * Storage modifiers like static, mut, const, ref, etc.
"keyword.storage.modifier" = { fg = "coals", modifiers = ["bold"]}

# * ||, +=, >
"operator" = "fire"

#"function"
#"function.builtin"
#"function.method"
"function.macro" = { bg = "cloud", modifiers = ["bold"] }
# * (preprocessor in C)
#"function.special"

# * Tags (e.g. <body> in HTML)
"tag" = { modifiers = ["bold"] }
#"tag.builtin"

#"namespace"

#"special"  # ??? IDK ???

#"markup"
"markup.heading" = { fg = "pomelo", modifiers = ["bold"] }
#"markup.heading.marker"
#"markup.heading.1"    # heading text for h1 through h6
#"markup.heading.2"
#"markup.heading.3"
#"markup.heading.4"
#"markup.heading.5"
#"markup.heading.6" 
"markup.list" = "pomelo"
#"markup.list.unnumbered"
#"markup.list.numbered"
#"markup.list.checked"
#"markup.list.unchecked"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
#"markup.link"
# * URLs pointed to by links
"markup.link.url" = { fg = "pomelo", underline = { style = "line" } }
# * non-URL link references
"markup.link.label" = { bg = "pomelo", modifiers = ["italic"] }
# * URL and image descriptions in links
"markup.link.text" = "mountain"
"markup.quote" = { fg = "mountain", modifiers = ["italic"] }
"markup.raw" = "lining"
#"markup.raw.inline"
#"markup.raw.block"

# * version control changes
#"diff"
"diff.plus" = "sky"
"diff.minus" = "coals"
"diff.delta" = "lining"
"diff.delta.moved" = "sun"

# # UI Elements

# * The following markup scopes are used for themeing the editor interface.
#"markup.normal"
#"markup.normal.completion"        # for completion doc popup UI
#"markup.normal.hover"             # for hover popup UI
# * markup.heading    [already defined above]
#"markup.heading.completion"       # for completion doc popup UI
#"markup.heading.hover"            # for hover popup UI
# * markup.raw        [ already defined above]
# * markup.raw.inline [ already defined above]
#"markup.raw.inline.completion"    # for completion doc popup UI
#"markup.raw.inline.hover"         # for hover popup UI

"ui.background" = { bg = "night" }
# * Picker separator below input line
#"ui.background.separator"

#"ui.cursor"   
#"ui.cursor.normal"    
#"ui.cursor.insert"    
#"ui.cursor.select"
# * Matching bracket etc.    
"ui.cursor.match" = { bg = "cloud", fg = "fire" }
# * Cursor with primary selection
#"ui.cursor.primary"
"ui.cursor.primary.normal" = { bg = "sun", fg = "cloud" }
"ui.cursor.primary.insert" = { bg = "fire", fg = "night" }
"ui.cursor.primary.select" = { bg = "melville", fg = "sun" }

# * Breakpoint indicator, found in the gutter
#"ui.debug.breakpoint"
# * Indicator for the line at which debugging execution is paused at, found in the gutter
#"ui.debug.active"
#"ui.gutter"
# * Gutter for the line the cursor is on
#"ui.gutter.selected"
# * Line at which debugging execution is paused at
#"ui.highlight.frameline"
# * Line numbers
"ui.linenr" = "fog"
# * Line number for the line the cursor is on
"ui.linenr.selected" = "sun"

# * Statusline
"ui.statusline" = { bg = "twilight", fg = "pomelo" }
# * Statusline (unfocused document)
"ui.statusline.inactive" = { bg = "twilight", fg = "melville" }
# * Statusline mode during normal mode (only if editor.color-modes is enabled)
"ui.statusline.normal" = { bg = "sun", fg = "twilight" }
# * Statusline mode during insert mode (only if editor.color-modes is enabled)
"ui.statusline.insert" = { bg = "fire", fg = "night" }
# * Statusline mode during select mode (only if editor.color-modes is enabled)
"ui.statusline.select" = { bg = "cloud", fg = "sun" }
# * Separator character in statusline
#"ui.statusline.separator"

# * Documentation popups (e.g. Space + k)
"ui.popup" = { bg = "twilight", fg = "pomelo" }
# * Prompt for multiple key options
#"ui.popup.info"
# * Borderlines separating splits
"ui.window" = { bg = "twilight", fg = "fire" }
# * Description box for commands
"ui.help" = { bg = "twilight", fg = "pomelo" }
# * Command prompts, popup text, etc.
"ui.text" = "sun"
"ui.text.focus"  = { bg = "cloud", fg = "sky" }
# * Same as ui.text but when the text is inactive (e.g. suggestions)
"ui.text.inactive" = { bg = "night", fg = "fog" }
# * The key: command text in ui.popup.info boxes
"ui.text.info" = { bg = "twilight", fg = "fire" }

"ui.virtual" = "fog"
# * Ruler columns (see the editor.rulers config)
"ui.virtual.ruler" = { bg = "twilight", fg = "pomelo"}
"ui.virtual.whitespace" = "fog"
"ui.virtual.indent-guide" = "fog"
# * Default style for inlay hints of all kinds
"ui.virtual.inlay-hint" = { bg = "cloud", fg = "fire" }
# * Style for inlay hints of kind parameter (LSPs are not required to set a kind)
#"ui.virtual.inlay-hint.parameter"
# * Style for inlay hints of kind type (LSPs are not required to set a kind)
#"ui.virtual.inlay-hint.type"
# * Soft-wrap indicator (see the editor.soft-wrap config)
#"ui.virtual.wrap"

# * Code and command completion menus
"ui.menu"         = { bg = "twilight", fg = "melville" }
# * Selected autocomplete item
"ui.menu.selected" = { bg = "cloud", fg = "sky" }
# * fg sets thumb color, bg sets track color of scrollbar
#"ui.menu.scroll"
# * For selections in the editing area
"ui.selection" = { bg = "cloud" }
"ui.selection.primary" = { bg = "cloud" }
# * Highlighted lines in the picker preview
"ui.highlight" = { bg = "coud", fg = "sky" }

# * The next four only matter if editor.cursorline is enabled in config.
"ui.cursorline.primary" = { bg = "twilight" } # The line of the primary cursor
"ui.cursorline.secondary" = { bg = "twilight" } # The lines of any other cursors
#"ui.cursorcolumn.primary"     # The column of the primary cursor
#"ui.cursorcolumn.secondary"   # The columns of any other cursors

# * The next four are for gutter indicators.
"warning" = "coals"
"error" = "sun"
"info" = "melville"
"hint" = "mountain"
# * For diagnostic indication in the editing area
#"diagnostic"
"diagnostic.hint"    = { underline = { style = "curl", color = "mountain" } }
"diagnostic.info"    = { underline = { style = "curl", color = "melville" } }
"diagnostic.warning" = { underline = { style = "curl", color = "sun" } }
"diagnostic.error"   = { underline = { style = "curl", color = "coals" } }

[palette]
night    = "#08040c"
twilight = "#101828"
cloud    = "#302c34"
fog      = "#404858"
melville = "#5080a8"
sky      = "#58b0e0"

mountain = "#807890"

coals  = "#e0500c"
fire   = "#f08020"
pomelo = "#f0a050"
sun    = "#f6d3a0"
lining = "#e8e0c8"
