# wa_budapest1.toml
#
# A Helix theme based on the CRAN `wesanderson` package's
# "GrandBudapest1 palette."
#
# author/maintainer: Dan(github.com/d2718)

# # Syntax Scopes

# * - Class attributes, HTML tag attributes
"attribute" = "burlap"

"type" = { modifiers = ["bold"] }
# * Primitive types provided by the language (int, usize)
"type.builtin" = { modifiers = ["italic"] }
#"type.enum"
"type.enum.variant" = { modifiers = [] }

#"constructor"

"constant" = "manila"
# * Special constants provided by the language (true, false, nil etc)
#"constant.builtin"
#"constant.builtin.boolean"
#"constant.character"
#"constant.character.escape"
#"constant.numeric"
#"constant.numeric.integer"
#"constant.numeric.float"

"string" = "clay"
#"string.regexp"
#"string.special"
#"string.special.path"
#"string.special.url"
# * Erlang/Elixir atoms, Ruby symbols, Clojure keywords
#"string.special.symbol"

# * Comments
"comment" = "latte"
# * Single line comments (//)
#"comment.line"
# * Block comments (e.g. (/* */)
#"comment.block"
# * Documentation comments (e.g. /// in Rust)
#"comment.block.documentation"

#"variable"
# * Reserved language variables (self, this, super, etc.)
"variable.builtin" = { fg = "coral", modifiers = ["bold"] }
# * Function parameters
"variable.parameter" = { fg = "coral" }
#"variable.other"  # ??? IDK ???
# * Fields of composite data types (e.g. structs, unions)
#"variable.other.member"

#"label"

"punctuation" = "burlap"
# * Commas, colons
#"punctuation.delimiter"
# * Parentheses, angle brackets, etc.
#"punctuation.bracket"
# * String interpolation brackets.
#"punctuation.special"

"keyword" = "burlap"
#"keyword.control"
# * if, else
#"keyword.control.conditional"
# * for, while, loop
#"keyword.control.repeat"
# * import, export
#"keyword.control.import"
#"keyword.control.return"
#"keyword.control.exception"
# * or, in
"keyword.operator" = { fg = "burlap", modifiers = ["bold"] }
# * Preprocessor directives (#if in C)
#"keyword.directive"
# * fn, func
#"keyword.function"
# * Keywords describing how things are stored
#"keyword.storage"
# * The type of something, class, function, var, let, etc.
#"keyword.storage.type"
# * Storage modifiers like static, mut, const, ref, etc.
"keyword.storage.modifier" = "salmon"

# * ||, +=, >
"operator" = { modifiers = ["bold"] }

#"function"
#"function.builtin"
#"function.method"
"function.macro" = { underline = { style = "dotted" } }
# * (preprocessor in C)
#"function.special"

# * Tags (e.g. <body> in HTML)
"tag" = { modifiers = ["bold"] }
#"tag.builtin"

#"namespace"

#"special"  # ??? IDK ???

#"markup"
"markup.heading" = { modifiers = ["bold"] }
#"markup.heading.marker"
#"markup.heading.1"    # heading text for h1 through h6
#"markup.heading.2"
#"markup.heading.3"
#"markup.heading.4"
#"markup.heading.5"
#"markup.heading.6" 
"markup.list" = "burlap"
#"markup.list.unnumbered"
#"markup.list.numbered"
#"markup.list.checked"
#"markup.list.unchecked"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
#"markup.link"
# * URLs pointed to by links
"markup.link.url" = { underline = { style = "line" } }
# * non-URL link references
"markup.link.label" = { underline = { style = "dotted" } }
# * URL and image descriptions in links
"markup.link.text" = "clay"
"markup.quote" = "clay"
"markup.raw" = "manila"
#"markup.raw.inline"
#"markup.raw.block"

# * version control changes
#"diff"
"diff.plus" = "ecru"
"diff.minus" = "salmon"
"diff.delta" = "clay"
"diff.delta.moved" = "manila"

# # UI Elements

# * The following markup scopes are used for themeing the editor interface.
#"markup.normal"
#"markup.normal.completion"        # for completion doc popup UI
#"markup.normal.hover"             # for hover popup UI
# * markup.heading    [already defined above]
#"markup.heading.completion"       # for completion doc popup UI
#"markup.heading.hover"            # for hover popup UI
# * markup.raw        [ already defined above]
# * markup.raw.inline [ already defined above]
#"markup.raw.inline.completion"    # for completion doc popup UI
#"markup.raw.inline.hover"         # for hover popup UI

"ui.background" = { bg = "cellar", fg = "ecru" }
# * Picker separator below input line
#"ui.background.separator"

"ui.cursor" = { fg = "cellar", bg = "ecru" }
#"ui.cursor.normal"
"ui.cursor.insert" = { bg = "salmon", fg = "cellar" }
"ui.cursor.select" = { bg = "latte", fg = "salmon" }
# * Matching bracket etc.    
"ui.cursor.match" = { bg = "latte", fg = "salmon" }
# * Cursor with primary selection
#"ui.cursor.primary"
#"ui.cursor.primary.normal"    
"ui.cursor.primary.insert" = { bg = "salmon", fg = "cellar" }
"ui.cursor.primary.select" = { bg = "latte", fg = "salmon" }
# * Breakpoint indicator, found in the gutter
#"ui.debug.breakpoint"
# * Indicator for the line at which debugging execution is paused at, found in the gutter
#"ui.debug.active"
#"ui.gutter"
# * Gutter for the line the cursor is on
#"ui.gutter.selected"
# * Line at which debugging execution is paused at
#"ui.highlight.frameline"
# * Line numbers
"ui.linenr" = "clay"
# * Line number for the line the cursor is on
"ui.linenr.selected" = "ecru"

# * Statusline
"ui.statusline" = { bg = "burgundy", fg = "manila" }
# * Statusline (unfocused document)
"ui.statusline.inactive" = { bg = "mocha", fg = "clay" }
# * Statusline mode during normal mode (only if editor.color-modes is enabled)
#"ui.statusline.normal"
# * Statusline mode during insert mode (only if editor.color-modes is enabled)
"ui.statusline.insert" = { bg = "salmon", fg = "cellar" }
# * Statusline mode during select mode (only if editor.color-modes is enabled)
"ui.statusline.select" = { bf = "mocha", fg = "salmon" }
# * Separator character in statusline
#"ui.statusline.separator"

# * Documentation popups (e.g. Space + k)
"ui.popup" = { fg = "manila", bg = "burgundy" }
# * Prompt for multiple key options
#"ui.popup.info"
# * Borderlines separating splits
"ui.window" = { bg = "burgundy", fg = "clay" }
# * Description box for commands
#"ui.help"
# * Command prompts, popup text, etc.
"ui.text" = { fg = "ecru" }
#"ui.text.focus"  
# * Same as ui.text but when the text is inactive (e.g. suggestions)
#"ui.text.inactive"
# * The key: command text in ui.popup.info boxes
#"ui.text.info"

#"ui.virtual"
# * Ruler columns (see the editor.rulers config)
"ui.virtual.ruler" = { bg = "burgundy" }
"ui.virtual.whitespace" = { fg = "latte" }
"ui.virtual.indent-guide" = { fg = "latte" }
# * Default style for inlay hints of all kinds
#"ui.virtual.inlay-hint"
# * Style for inlay hints of kind parameter (LSPs are not required to set a kind)
#"ui.virtual.inlay-hint.parameter"
# * Style for inlay hints of kind type (LSPs are not required to set a kind)
#"ui.virtual.inlay-hint.type"
# * Soft-wrap indicator (see the editor.soft-wrap config)
#"ui.virtual.wrap"

# * Code and command completion menus
"ui.menu" = { bg = "burgundy", fg = "manila" }
# * Selected autocomplete item
"ui.menu.selected" = { bg = "mocha", fg = "ecru" }
# * fg sets thumb color, bg sets track color of scrollbar
#"ui.menu.scroll"
# * For selections in the editing area
"ui.selection" = { bg = "mocha" }
"ui.selection.primary" = { bg = "mocha" }
# * Highlighted lines in the picker preview
"ui.highlight" = { bg = "mocha", fg = "ecru" }

# * The next four only matter if editor.cursorline is enabled in config.
"ui.cursorline.primary" = { bg = "burgundy" }       # The line of the primary cursor
#"ui.cursorline.secondary"     # The lines of any other cursors
"ui.cursorcolumn.primary" = { bg = "burgundy" }    # The column of the primary cursor
#"ui.cursorcolumn.secondary"   # The columns of any other cursors

# * The next four are for gutter indicators.
"warning" = "clay"
"error"   = "salmon"
"info"    = "manila"
"hint"    = "latte"
# * For diagnostic indication in the editing area
#"diagnostic"
"diagnostic.hint"    = { underline = { style = "curl", color = "latte"} }
"diagnostic.info"    = { underline = { style = "curl", color = "latte"} } 
"diagnostic.warning" = { underline = { style = "curl", color = "latte"} }
"diagnostic.error"   = { underline = { style = "curl", color = "latte"} }
[palette]

mocha = "#403120"
latte = "#805341"

burlap = "#e4985a"
manila = "#f1bb7b" #
ecru   = "#f8dfc1"

coral   = "#f69271"
salmon = "#fd6467" #

cellar   = "#180606" 
burgundy = "#5b1a18" #

clay = "#d67236" #
